### PR TITLE
shares g7

### PR DESCRIPTION
**Pull request by jm-rivera**

### CODE REVIEW

**Comment by jm-rivera** [comment]
@nupur-parikh this data is from 2012 because of data completeness to produce the multilateral imputations

**Comment by nupur-parikh** [comment]
This is great, thank you!! is it possible to split bilateral vs. multilateral in this so we can see how it differs over the same tiem period?

**Comment by jm-rivera** [comment]
@nupur-parikh would you mind opening a new issue with that?

**Comment by nupur-parikh** [comment]
You create done already here: https://github.com/ONEcampaign/data_stories/issues/9#issue-2534252751

**Comment by jm-rivera** [comment]
aha! though if you want something g7 specific, please still create another so that i don't forget (that one i take to be overall, rather than g7)

**Comment by nupur-parikh** [comment]
Both would be helpful, new issue for G7 only here: https://github.com/ONEcampaign/data_stories/issues/18

Thank you :)

**Pull request merged**
